import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Breaking Cake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Breaking Cake</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="Cursor-pointer"/>
              </li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
              <li></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Something</h2>
            <h3 className="text-2xl py-2">Something Something</h3>
            <p className="text-md py-5 leading-8 text-gray-800">Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat rem perspiciatis cumque fugit possimus voluptas assumenda doloribus animi aliquid commodi dolores, nulla quae delectus voluptatem tempora, libero nam explicabo blanditiis!
            Molestiae aperiam totam accusamus iste, excepturi vitae ad, iusto sunt, laudantium nesciunt obcaecati fugiat ex id asperiores adipisci voluptas quibusdam optio. Vel, quos iusto voluptatibus amet ab dignissimos id asperiores.</p>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          

          </div>
        </section>

      </main>

    </div>
  )
}
