import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/main_cake.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from 'next/legacy/image'
import cake1 from "../public/1.jpg";
import cake2 from "../public/2.jpg";
import cake3 from "../public/3.jpg";
import cake4 from "../public/4.jpg";
import cake5 from "../public/5.jpg";
import cake6 from "../public/6.jpg";
import cake7 from "../public/7.jpg";
import cake8 from "../public/8.jpg";
import cake9 from "../public/9.jpg";
import cake10 from "../public/10.jpg";

import React from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Breaking Bakes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Breaking Bakes</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Something
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            Breaking Bakes
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            Baking & Cake Decoration.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Baking is the process of cooking food in an oven using dry heat. Cake decoration is the process of adding designs and decorations to cakes.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-md w-80 h-80 relative overflow-hidden mt-20 md:h-80 md:w-80">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam vel ipsum tempore?<span className="text-teal-500">Lorem</span>Lorem ipsum dolor sit amet.

            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">lorem</h3>
              <p className="py-2">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi dicta aliquam ab cumque?
              </p>
              <h4 className="py-4 text-teal-600">Lorem ipsum dolor sit amet.</h4>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">lorem</h3>
              <p className="py-2">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi dicta aliquam ab cumque?
              </p>
              <h4 className="py-4 text-teal-600">Lorem ipsum dolor sit amet.</h4>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">lorem</h3>
              <p className="py-2">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi dicta aliquam ab cumque?
              </p>
              <h4 className="py-4 text-teal-600">Lorem ipsum dolor sit amet.</h4>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod, ducimus?
              <span className="text-teal-500">lorem</span>
              Lorem, ipsum dolor.<span className="text-teal-500">lorem </span>
Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, quo fugiat? Nam rerum rem adipisci neque iste beatae animi. Quo officiis eaque excepturi nisi fugiat beatae consequatur enim nobis cum!
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake1}
              />
            </div>
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake2}
              />
            </div>
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake3}
              />
            </div>
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake4}
              />
            </div>
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake5}
              />
            </div>
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake6}
              />
            </div>
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake7}
              />
            </div>
            <div className="basis-1/5 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={cake8}
              />
            </div>
            
          </div>
        </section>
      </main>
    </div>
  );
}