import Head from "next/head";
import {
	AiFillTwitterCircle,
	AiFillLinkedin,
	AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/main_cake.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from 'next/legacy/image'
import cake1 from "../public/1.jpg";
import cake2 from "../public/2.jpg";
import cake3 from "../public/3.jpg";
import cake4 from "../public/4.jpg";
import cake5 from "../public/5.jpg";
import cake6 from "../public/6.jpg";
import cake7 from "../public/7.jpg";
import cake8 from "../public/8.jpg";
import cake9 from "../public/9.jpg";
import cake10 from "../public/10.jpg";

import dec1 from "../public/dec1.png";
import dec3 from "../public/dec3.png";
import dec2 from "../public/dec2.png";
import dec5 from "../public/dec5.png";
import dec4 from "../public/dec4.png";

import React from "react";


export default function Home() {
	const [darkMode, setDarkMode] = useState(true);

	return (
    <div className={darkMode ? "dark" : ""}>
<Head>
<title>Breaking Bakes</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>
<main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
<section className="min-h-screen">
	<nav className="py-10 mb-12 flex justify-between dark:text-white">
		<h1 className="font-burtons text-xl">Breaking Bakes</h1>
		<ul className="flex items-center">
		<li>
			<BsFillMoonStarsFill
			onClick={() => setDarkMode(!darkMode)}
			className=" cursor-pointer text-2xl"
			/>
		</li>
		<li>
			<a
			className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
			href="#"
			>
			Pasteles
			</a>
		</li>
		<li>
			<a
			className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
			href="#"
			>
			Adornos
			</a>
		</li>
		<li>
			<a
			className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
			href="#"
			>
			Pedidos
			</a>
		</li>
		</ul>
</nav>
<div className="text-center p-10 py-10">
	<h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
	Breaking Bakes
	</h2>
	<h3 className="text-2xl py-2 dark:text-white md:text-3xl">
	Baking & Cake Decoration.
	</h3>
	<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
	Baking is the process of cooking food in an oven using dry heat. Cake decoration is the process of adding designs and decorations to cakes.
	</p>
	<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
	<AiFillTwitterCircle />
	<AiFillLinkedin />
	<AiFillYoutube />
	</div>
	<div className="mx-auto bg-gradient-to-b from-teal-500 rounded-md w-80 h-80 relative overflow-hidden mt-10 md:h-80 md:w-80">
	<Image src={deved} layout="fill" objectFit="cover" />
	</div>
</div>
</section>
<section>
	<div>
			<h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam vel ipsum tempore?<span className="text-teal-500">Lorem</span>Lorem ipsum dolor sit amet.

			</p>
			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum!
			</p>
		</div>
		<div className="lg:flex gap-10">
			<div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
			<Image src={design} width={100} height={100} />
			<h3 className="text-lg font-medium pt-8 pb-2 ">lorem</h3>
			<p className="py-2">
			Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi dicta aliquam ab cumque?
			</p>
			<h4 className="py-4 text-teal-600">Lorem ipsum dolor sit amet.</h4>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			</div>
			<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
			<Image src={consulting} width={100} height={100} />
			<h3 className="text-lg font-medium pt-8 pb-2 ">lorem</h3>
			<p className="py-2">
			Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi dicta aliquam ab cumque?
			</p>
			<h4 className="py-4 text-teal-600">Lorem ipsum dolor sit amet.</h4>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			</div>
			<div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
			<Image src={consulting} width={100} height={100} />
			<h3 className="text-lg font-medium pt-8 pb-2 ">lorem</h3>
			<p className="py-2">
			Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nisi dicta aliquam ab cumque?
			</p>
			<h4 className="py-4 text-teal-600">Lorem ipsum dolor sit amet.</h4>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			<p className="text-gray-800 py-1">lorem</p>
			</div>
		</div>
	</section>
	<section className="py-10">
		<div>
			<h3 className="text-6xl py-1 dark:text-white text-center uppercase">Pasteles</h3>
		</div>
		<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  px-10 rounded-xl">

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake1} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO LIGHT DE PLÁTANO Y MANZANA<br></br></h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>
		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake2} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO CON COBERTURA DE CHOCOLATE</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake3} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO DE SEMILLAS DE CHÍA</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake4} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO MARMOLADO CON FRAMBUESAS</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake5} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO PLUMCAKE DE AGUACATE</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake6} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO DE CHOCOLATE</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake7} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO DE MANZANA<br></br></h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake8} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO DE NARANJA<br></br></h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake9} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO MADEIRA</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={cake10} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black ">BIZCOCHO <br></br>"1, 2, 3"</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>
			
		</div>
	</section>

	<section className="py-10">
		<div>
		<h3 className="text-6xl py-1 dark:text-white text-center uppercase">Adornos</h3>
		</div>
		<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  px-10 rounded-xl">

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={dec1} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black uppercase ">TOPPER de NUmero<br></br></h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>
		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={dec2} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black uppercase ">topper de cocodrilo</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={dec3} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black uppercase ">Topper de oveja negra</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={dec4} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black uppercase ">Topper de perro</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>

		<div className="text-center basis-1/6 flex-1 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
			<Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={dec5} />
			<div>
			<h3 className="text-2xl py-1 dark:text-black uppercase">Star Wars Toppers</h3>

			<p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
			<br></br><span className="text-teal-500"> $50 USD</span>
			</p>
			</div>
		</div>
		</div>
	</section>
	<section>

		<div className="text-2xl text-center py-10 px-10">
			<h1 className="text-center py-4">Realiza el pedido de tu pastel</h1>
			<h2 className="py-5">Proporcionanos tus datos de contacto</h2>
			</div>
			
		<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  px-10 rounded-xl justify-center">
			<label> Nombre: </label>
			<input className="shadow-md border-double" type="text" id="nombre"></input>
			<label> Telefono: </label>
			<input className="shadow-md" type="tel" id="telefono" maxLength="10"></input>
			<label> Correo electronico: </label>
			<input className="shadow-md" type="email" id="correo"></input>
			<label> Descripcion general del pastel: </label>
			<input className="shadow-md" type="text" id="descripcion"></input>
		</div>
			<div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  px-10 rounded-xl justify-center">
				<div className="basis-1/6 bg-white rounded-xl px-5 py-10 shadow-lg p-10 ">
				<p className="text-5xl pb-10">Elige el sabor(s) </p>
				<form action="" className="text-left">
					<input type="checkbox" id="chocolate" value="Chocolate"></input>
					<label> BIZCOCHO LIGHT DE PLÁTANO Y MANZANA</label>
					<br></br>
					<input type="checkbox" id="fresa" value="fresa"></input>
					<label> BIZCOCHO CON COBERTURA DE CHOCOLATE</label>
					<br></br>
					<input type="checkbox" id="galleta" value="galleta"></input>
					<label> BIZCOCHO DE SEMILLAS DE CHÍA</label>
					<br></br>
					<input type="checkbox" id="conbinado" value="conbinado"></input>
					<label> BIZCOCHO MARMOLADO CON FRAMBUESAS</label>
					<br></br>
					<input type="checkbox" id="spunk" value="spunk"></input>
					<label> BIZCOCHO PLUMCAKE DE AGUACATE</label>
					<br></br>
					<input type="checkbox" id="salvadoreño" value="salvadoreño"></input>
					<label> BIZCOCHO DE MANZANA</label>
					<br></br>
					<input type="checkbox" id="chocolate" value="Chocolate"></input>
					<label> BIZCOCHO DE NARANJA</label>
					<br></br>
					<input type="checkbox" id="fresa" value="fresa"></input>
					<label> BIZCOCHO MADEIRA</label>
					<br></br>
					<input type="checkbox" id="galleta" value="galleta"></input>
					<label> BIZCOCHO "1, 2, 3"</label>
					<br></br>
					</form>
				</div>
				<div className="basis-1/6 bg-white rounded-xl px-5 py-10 shadow-lg p-10">
				<p className="text-5xl pb-10">Elige el adorno(s) </p>
				<form action="" className="text-left">
					<input type="checkbox" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"></input>
					<label> TOPPER DE NUMERO</label>
					<br></br>
					<input type="checkbox" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"></input>
					<label> TOPPER DE COCODRILO</label>
					<br></br>
					<input type="checkbox" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"></input>
					<label> TOPPER DE OVEJA NEGRA</label>
					<br></br>
					<input type="checkbox" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"></input>
					<label> TOPPER DE PERRO</label>
					<br></br>
					<input type="checkbox" className="w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"></input>
					<label> STAR WARS TOPPERS</label>
					<br></br>
					</form>
				</div>
			</div>

		<div  className="justify-center">
			<button type="submit" onClick="alert('Tu pedido fue enviado')" className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8">Enviar mi pedido</button>
		</div>
		</section>
	</main>
	</div>
);
}